# Generated by Django 2.2.6 on 2021-08-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='*Поле обязательно для заполнения', verbose_name='Текст Поста'),
        ),
    ]
